apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "taiga.fullname" . }}
  labels:
{{ include "taiga.labels" . | indent 4 }}
data:
  DEBUG: {{ .Values.taiga.debug | default "False" | quote }}
  TAIGA_HOSTNAME: {{ required "taiga.apiserver must be set" .Values.taiga.apiserver }}
  TAIGA_SSL: "false"
  TAIGA_SSL_BY_REVERSE_PROXY: {{ .Values.taiga.behindTlsProxy | ternary "True" "False" | quote }}
  TAIGA_DB_HOST: {{ required "taiga.dbHost must be set" .Values.taiga.dbHost }}
  TAIGA_DB_NAME: {{ required "taiga.dbName must be set" .Values.taiga.dbName }}
  TAIGA_DB_USER: {{ required "taiga.dbUser must be set" .Values.taiga.dbUser }}
  TAIGA_ENABLE_EMAIL: {{ .Values.taiga.emailEnabled | ternary "True" "False" | quote }}
{{- if .Values.taiga.emailEnabled }}
  TAIGA_EMAIL_FROM: {{ .Values.taiga.emailFrom | default "taiga@example.com" |  quote }}
  TAIGA_EMAIL_USE_TLS: {{ .Values.taiga.emailUseTls | default true | ternary "True" "False" | quote }}
  TAIGA_EMAIL_HOST: {{ required "taiga.emailSmtpHost must be set" .Values.taiga.emailSmtpHost | quote }}
  TAIGA_EMAIL_PORT: {{ default 587 .Values.taiga.emailSmtpPort | quote }}
  TAIGA_EMAIL_USER: {{ required "taiga.emailSmtpUser must be set" .Values.taiga.emailSmtpUser | quote }}
{{- end }}
{{- if .Values.taiga.ldap.enabled }}
  LDAP_AUTH_ENABLE: "True"
  LDAP_START_TLS: {{ .Values.taiga.ldap.use_tls | default "False" |  quote }}
  LDAP_SERVER: {{ .Values.taiga.ldap.ldap_server | quote }}
  LDAP_PORT: {{ .Values.taiga.ldap.port | default 389 | quote }}
  LDAP_BIND_DN: {{ .Values.taiga.ldap.bind_dn | default "" |  quote }}
  LDAP_SEARCH_BASE: {{ .Values.taiga.ldap.base_dn |  quote }}
  LDAP_BIND_PASSWORD: {{ .Values.taiga.ldap.password |  quote }}
  LDAP_USERNAME_ATTRIBUTE: {{ .Values.taiga.ldap.username_attribute | default "uid" |  quote }}
  LDAP_EMAIL_ATTRIBUTE: {{ .Values.taiga.ldap.email_attribute | default "mail" |  quote }}
  LDAP_FULL_NAME_ATTRIBUTE: {{ .Values.taiga.ldap.full_name_attribute | default "displayName" |  quote }}
  LDAP_FALLBACK: {{ .Values.taiga.ldap.fallback | default "normal" |  quote }}
  LDAP_SAVE_LOGIN_PASSWORD: {{ .Values.taiga.ldap.save_password | default "False" |  quote }}
  LDAP_SEARCH_FILTER_ADDITIONAL: {{ .Values.taiga.ldap.filter | default "" | quote }}
{{- end }}
